language: python
sudo: required
dist: trusty
python:
- 2.7
services:
- docker
install:
- docker build -f Dockerfile-py${TRAVIS_PYTHON_VERSION} -t digitaldomain/qt_py_convert
  .
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- docker run --rm -v $(pwd):/QtPyConvert digitaldomain/qt_py_convert
deploy:
  provider: pypi
  user: ahuge
  password:
    secure: G+pnrNDpW0hcswE6r0I2YuoTcyQB3+6Dp0cFesZ66SbJYjZR1XL1cKPFkOEylCIQMAukzWpwLBEUjVE7iLqJ8rqXdSOyPHgmyVg+aaLZwuYqRKXSyYsWWs4x7fQ3NBcPtInYZRuPjio66wiCKOxKzw6+Bto5SiMBIoITMEJrbkQ6UYTgTkcQdsl2G9Ud8oL6tZWp4Tve8+5x7Emash3j5gxVC31O/2ec39jyZ2L1wxpuTIYJegXNAntB47u5fNOfxe47l7DJt1eRO/C2HEio/S6Ar2jyYJoMjD/kqMNBSCHACCS8dNJJAbEZT3DLqs1XeB20l1CmgSWklLHWpIoe7P2qw0zdYiXJhsvRdOxO8JcMPUrpPSlDreq+vuKlqHBygeobMyw3P7d9iI+3hzmwXqopfv9lxHxnFcTsuWDURzlwrmlfCBJRxq6FtcTL7KpOZGQVEzEtUAVSvUolao+dm6lDbDx/vIl4YkEA7fPc0lO4ARK4cwEAzE3TzTU1CyMMeIZMdvGW7RaJSi0pSlT4aso+dELtF7vdoZfPVUQ99XrDibpMvalQr5FsIfll1CZvVylfeHv3NfEA8XygZLVK6GOKwy3LdZCwvY21aitAM3xzDaeSnfhwaSDfSa7c7QMSrOQD9tOTcRs202TcNErwbJaGqR4FXlpxLfkt6aBXd6I=
  distributions: sdist bdist_wheel
  on:
    branch: feature-pypi_releases
    repo: digitaldomain/QtPyConvert
env:
  global:
    secure: L9i7s8SbNCnBRcOGbd3sfW//CnyVPkUfF+xvBzyfC8K1oj2E0gwOT19p7vHgyHukNI5QZEJxCdAUADTucdg14ju1NM6QenF+VeHjgCJXrU+Og1E0LK+F3171MudbgX81+QHrwQS2ycTDPfTfb5NmaN2XFIzplniXATehc4quS7Itt7KDGlQXSLI9wjOdMNROxgTJj4p+/+Ru6mNuufEsvgyYMlcS7LirCeX51zuMHvmBIxvnAMVOKZFje5rb8j/toexPXMXI/Wcf5aduz4nntsE9A7iKyPizvh2QO3HYkMmSYgsat3vjJdP8doBHL8luTT4EfvjOIGpuEotj6nrMN/Jj9WIZwv6oFcjvwr5dyCOAcDiY7uuJ4ipfBItFXPfQr5fHRuY5P3/5JlnWvKFpSymX/PEbsfLBzBXXQbxp+r17Cb7WDQ2G4HV6cmfSK3hyuLHXjoVhRLKsxRyYGDEn3qAg/LY+g19apftb83mI2Cx0l91leFxdAym4u7kk3RWAiUpa7h5Sdw5395ZdXxQjqFrtb99jgKcKDcumdRCCGmq9IblA1F19ySe7AYbD3H0vpOY4G4ghntXzkwjsNueexgCtH4IKFpTTdSsGWdZcpG58R4Gs1P9qs+4xQ31gpgJij2oqFz3U7vlxZ2ISYfT+yJlwRnYwef9EU6/i0Dopol0=
