language: python
sudo: required
dist: trusty
python:
- 2.7
services:
- docker
install:
- docker build -f Dockerfile-py${TRAVIS_PYTHON_VERSION} -t digitaldomain/qt_py_convert
  .
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- docker run --rm -v $(pwd):/QtPyConvert digitaldomain/qt_py_convert


deploy:
  provider: pypi
  user: ahuge
  password: 
    secure: "G+pnrNDpW0hcswE6r0I2YuoTcyQB3+6Dp0cFesZ66SbJYjZR1XL1cKPFkOEylCIQMAukzWpwLBEUjVE7iLqJ8rqXdSOyPHgmyVg+aaLZwuYqRKXSyYsWWs4x7fQ3NBcPtInYZRuPjio66wiCKOxKzw6+Bto5SiMBIoITMEJrbkQ6UYTgTkcQdsl2G9Ud8oL6tZWp4Tve8+5x7Emash3j5gxVC31O/2ec39jyZ2L1wxpuTIYJegXNAntB47u5fNOfxe47l7DJt1eRO/C2HEio/S6Ar2jyYJoMjD/kqMNBSCHACCS8dNJJAbEZT3DLqs1XeB20l1CmgSWklLHWpIoe7P2qw0zdYiXJhsvRdOxO8JcMPUrpPSlDreq+vuKlqHBygeobMyw3P7d9iI+3hzmwXqopfv9lxHxnFcTsuWDURzlwrmlfCBJRxq6FtcTL7KpOZGQVEzEtUAVSvUolao+dm6lDbDx/vIl4YkEA7fPc0lO4ARK4cwEAzE3TzTU1CyMMeIZMdvGW7RaJSi0pSlT4aso+dELtF7vdoZfPVUQ99XrDibpMvalQr5FsIfll1CZvVylfeHv3NfEA8XygZLVK6GOKwy3LdZCwvY21aitAM3xzDaeSnfhwaSDfSa7c7QMSrOQD9tOTcRs202TcNErwbJaGqR4FXlpxLfkt6aBXd6I="
  distributions: "sdist bdist_wheel" # Your distributions here
  on:
    branch: feature-pypi_releases
    repo: digitaldomain/QtPyConvert
