language: python
sudo: required
dist: trusty
python:
- 2.7
services:
- docker
install:
- docker build -f Dockerfile-py${TRAVIS_PYTHON_VERSION} -t digitaldomain/qt_py_convert
  .
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- docker run --rm -v $(pwd):/QtPyConvert digitaldomain/qt_py_convert


deploy:
  provider: pypi
  user: ahuge
  password: 
    secure: "ngjXAEktLB/xVICzdnr3dzuU9JQIzMlkV4w3dP6knkr2HiZng2eIjZInIh87qmNN0LODd1zkBFOk9GhDIKcDBNdql+LPmBSuYpmhTrQBRENLG8uL9+THzXg/uDqEn23walE68HF6c/J8EguJ2GaPRPgCmJxtfP29mSLB0mo2I06D29YTcbfGA+n76W7jqq5QzBdxOixy7Rzhp6FOJuLMNVOmx2vFsw8b8JNVvpwF9z07QFtfz7yoEHAKVs0+brC8DJZPFVhk9u+0/k7vfDYCOFCwZ21hmNhSTdP07qt73E6BGy2p+f/JVXxtViKXbjyqbGD25a0IUPFeeskLKLzYfJl+td4Unm63RwXpDsjcFLrImflUmwVTtaFcJ6CDEm5QxX0tAR3CV15x3rYVFXiq3n6sxdKWWSUFbYk/Ts7LwTCzz8RbWuHtv4yZzuFG5OPLeZ94V+r6VLCV6Et7PooVd0ZmMAlLTjscTctFc1SwfIjywBMiw5Km2F+o8HFOmPSv2ZG94U06rLzIbxtNIZFCm1qrwPIFGgEbS6ZsxjrvzcJDLbU8snYuTjd6g1lbzlsCcuVERa3JPLasIoibHv+tODrU8ACYtrh1fHQc4G3qjDe5YwnRYehHKDsX4clxhoi7gn0hv61cWYzR5VP5GoBIomqhUfQf5J2waseV2vyL4k8="
  distributions: "sdist bdist_wheel" # Your distributions here
  server: https://test.pypi.org/legacy/ # Remove for deployment to official PyPi repo
  on:
    branch: feature-pypi_releases
    repo: digitaldomain/QtPyConvert
